// All 15 members – including leaderboard position, tournaments, detailed profile
export const MEMBERS = [
  {
    username: "LunarWarden",
    password: "goldenkey",
    profile: {
      fullName: "Cdr. Kaelen 'Voidcaller' Ashford",
      role: "Leader",            // Leader or Member
      highestRank: "Grand Warlord",
      favoriteHeroes: ["Lunar Priestess", "Shadow Wolf", "Eclipse Knight"],
      favoriteLanes: ["Mid", "Jungle"],
      privateProfileLink: "https://lunarlegends.gg/warden",
      avatarIcon: "fa-crown",
      quote: "The moon's shadow is our greatest weapon.",
      joined: "Cycle I · Founder",
      reputation: "LEGENDARY (Obsidian Tier)",
      lunarCredits: 87400,
      missionsComplete: 47,
    },
    stats: { agility: 94, strategy: 99, lunarPotency: 97, resilience: 92 },
    achievements: ["Moon Reaper", "Eclipse Warden", "Unbroken Vow"],
    tournamentsWon: ["Lunar Cup 2024", "Obsidian Gauntlet", "Crescent Clash"],
    squadLeaderboardPosition: 1,
    activeMission: "Raid: Obsidian Shardheart — Eliminate Abyssal General",
    specialties: ["Tactical Override", "Void Slash", "Lunar Phalanx"],
    recentActions: ["Liberated Helios Outpost", "Recovered Aureolin Codex", "Neutralized Umbral Assassins"],
    progressToNextRank: 78,
    crescentBlessing: "Lunar Totem · Level 9"
  },
  {
    username: "Aurelius",
    password: "goldenflame",
    profile: {
      fullName: "Darius 'Aurelius' Sol",
      role: "Leader",
      highestRank: "Eternal Sentinel",
      favoriteHeroes: ["Solar Phoenix", "Ancient One", "Flame Warden"],
      favoriteLanes: ["Top", "Support"],
      privateProfileLink: "https://lunarlegends.gg/aurelius",
      avatarIcon: "fa-dragon",
      quote: "From obsidian ashes, the golden flame is reborn.",
      joined: "Cycle O (Founder)",
      reputation: "MYTHIC (Aureolin Paragon)",
      lunarCredits: 158200,
      missionsComplete: 112,
    },
    stats: { agility: 88, strategy: 100, lunarPotency: 100, resilience: 98 },
    achievements: ["Eternal Ember", "Godslayer", "Primeval Sovereign", "Flame of Genesis"],
    tournamentsWon: ["Primordial Cup", "Golden Era Invitational", "Crescent Crown"],
    squadLeaderboardPosition: 2,
    activeMission: "Purge the Corrupted Lunar Heart · Grand Exorcism",
    specialties: ["Golden Aegis", "Purifying Inferno", "Timeless Wisdom"],
    recentActions: ["Sealed rift in the Abyss", "Blessed new recruits", "Defeated Shadow Leviathan"],
    progressToNextRank: 100,
    crescentBlessing: "Lunar Blessing · Ascended"
  },
  {
    username: "StellarFlare",
    password: "cometblaze",
    profile: {
      fullName: "Lyra 'Solar Flare' Chen",
      role: "Member",
      highestRank: "Radiant Captain",
      favoriteHeroes: ["Sunstrike", "Nova Weaver"],
      favoriteLanes: ["Mid", "ADC"],
      privateProfileLink: "https://lunarlegends.gg/stellarflare",
      avatarIcon: "fa-sun",
      quote: "Burn brighter than any star, but honor the eclipse.",
      joined: "Cycle III",
      reputation: "RADIANT Vanguard",
      lunarCredits: 48700,
      missionsComplete: 29,
    },
    stats: { agility: 86, strategy: 91, lunarPotency: 98, resilience: 79 },
    achievements: ["Solar Nova", "Plasma Forger", "Stellar Emissary"],
    tournamentsWon: ["Helios Championship"],
    squadLeaderboardPosition: 3,
    activeMission: "Stabilize the Nexus Reactor · Energy Surge",
    specialties: ["Solar Lance", "Radiant Overload", "Photon Shield"],
    recentActions: ["Boosted Core Efficiency +34%", "Defeated Pyroclast Titan", "Upgraded Helios Array"],
    progressToNextRank: 45,
    crescentBlessing: "Crescent Spark · Level 6"
  },
  {
    username: "ShadowLynx",
    password: "nightsprint",
    profile: {
      fullName: "Riven 'Shadowstrike' Moroz",
      role: "Member",
      highestRank: "Ghost Operative",
      favoriteHeroes: ["Nightfang", "Umbra Assassin"],
      favoriteLanes: ["Jungle", "Roam"],
      privateProfileLink: "https://lunarlegends.gg/shadowlynx",
      avatarIcon: "fa-paw",
      quote: "Silence before the golden strike.",
      joined: "Cycle IV",
      reputation: "ELUSIVE (Phantom Protocol)",
      lunarCredits: 29300,
      missionsComplete: 33,
    },
    stats: { agility: 99, strategy: 82, lunarPotency: 85, resilience: 77 },
    achievements: ["Ghost Walker", "Eternal Shadow", "Noctis Exemplar"],
    tournamentsWon: ["Stealth Masters", "Midnight Rumble"],
    squadLeaderboardPosition: 4,
    activeMission: "Infiltrate Crimson Bastion · Steal War Data",
    specialties: ["Shadowstep", "Night Ambush", "Void Cloak"],
    recentActions: ["Sabotaged enemy coms", "Rescued undercover agent", "Recovered forbidden schematics"],
    progressToNextRank: 62,
    crescentBlessing: "Noctis Shroud · Level 7"
  },
  // 11 more members (total 15). I'll add concise entries for brevity, but each has full data.
  {
    username: "FrostHowl",
    password: "icewolf",
    profile: { fullName: "Bjorn 'Frostfang' Ironclaw", role: "Member", highestRank: "Winter Warden", favoriteHeroes: ["Ice Wolf", "Glacial Shaman"], favoriteLanes: ["Top", "Support"], privateProfileLink: "#", avatarIcon: "fa-wolf-pack-battalion", quote: "The frozen moon watches over us.", joined: "Cycle V", reputation: "FROSTBORN", lunarCredits: 21000, missionsComplete: 18 },
    stats: { agility: 78, strategy: 85, lunarPotency: 88, resilience: 95 },
    achievements: ["Frostbitten", "Icebound Conqueror"],
    tournamentsWon: ["Winter's Grasp"],
    squadLeaderboardPosition: 5,
    activeMission: "Defend the Northern Rift",
    specialties: ["Frost Armor", "Howling Blizzard"],
    recentActions: ["Repelled frost giants", "Saved trapped scouts"],
    progressToNextRank: 30,
    crescentBlessing: "Frozen Crescent · Level 4"
  },
  {
    username: "EmberClaw",
    password: "firehowl",
    profile: { fullName: "Sera 'Ember' Volkov", role: "Member", highestRank: "Ashen Berserker", favoriteHeroes: ["Magma Bear", "Cinder Wolf"], favoriteLanes: ["Jungle", "Top"], privateProfileLink: "#", avatarIcon: "fa-fire", quote: "Burn the night.", joined: "Cycle VI", reputation: "ASHEN", lunarCredits: 18900, missionsComplete: 14 },
    stats: { agility: 88, strategy: 70, lunarPotency: 84, resilience: 82 },
    achievements: ["Wildfire", "Emberstorm"],
    tournamentsWon: ["Blazing Duel"],
    squadLeaderboardPosition: 6,
    activeMission: "Scorch the Abyss nest",
    specialties: ["Fire Roar", "Cinder Trail"],
    recentActions: ["Burnt enemy siege", "Forged new weapons"],
    progressToNextRank: 28,
    crescentBlessing: "Ember Crescent · Level 5"
  },
  {
    username: "Nightshade",
    password: "poisonivy",
    profile: { fullName: "Morwen 'Nightshade' Vex", role: "Member", highestRank: "Venom Adept", favoriteHeroes: ["Widow's Kiss", "Shadowroot"], favoriteLanes: ["Mid", "Roam"], privateProfileLink: "#", avatarIcon: "fa-skull", quote: "Silence is venomous.", joined: "Cycle V", reputation: "SHADOW", lunarCredits: 16700, missionsComplete: 21 },
    stats: { agility: 96, strategy: 88, lunarPotency: 72, resilience: 68 },
    achievements: ["Toxic Touch", "Ghost Venom"],
    tournamentsWon: ["Venom Cup"],
    squadLeaderboardPosition: 7,
    activeMission: "Poison the enemy supplies",
    specialties: ["Nerve Toxin", "Shadow Strike"],
    recentActions: ["Assassinated high value target", "Planted false intel"],
    progressToNextRank: 55,
    crescentBlessing: "Nocturnal Fang · Level 5"
  },
  {
    username: "StormCrest",
    password: "thunderwolf",
    profile: { fullName: "Ragnar 'Storm' Ironhide", role: "Member", highestRank: "Tempest Lord", favoriteHeroes: ["Storm Wolf", "Thunder Shaman"], favoriteLanes: ["Top", "Jungle"], privateProfileLink: "#", avatarIcon: "fa-cloud-bolt", quote: "Roar like thunder.", joined: "Cycle IV", reputation: "TEMPEST", lunarCredits: 23400, missionsComplete: 26 },
    stats: { agility: 81, strategy: 87, lunarPotency: 91, resilience: 86 },
    achievements: ["Lightning Caller", "Stormbreaker"],
    tournamentsWon: ["Thunderdome"],
    squadLeaderboardPosition: 8,
    activeMission: "Calm the electric rifts",
    specialties: ["Chain Lightning", "Storm Shield"],
    recentActions: ["Defeated Tempest Wyrm", "Repaired energy conduits"],
    progressToNextRank: 48,
    crescentBlessing: "Storm Crescent · Level 6"
  },
  {
    username: "IronMane",
    password: "shieldwolf",
    profile: { fullName: "Greta 'Iron' Stonewall", role: "Member", highestRank: "Bulwark Sentinel", favoriteHeroes: ["Aegis Bear", "Fortress Wolf"], favoriteLanes: ["Support", "Top"], privateProfileLink: "#", avatarIcon: "fa-shield-halbed", quote: "Unyielding as the mountain.", joined: "Cycle III", reputation: "IRONWILL", lunarCredits: 31200, missionsComplete: 35 },
    stats: { agility: 70, strategy: 92, lunarPotency: 80, resilience: 99 },
    achievements: ["Immovable", "Wall of Honor"],
    tournamentsWon: ["Shield Slam"],
    squadLeaderboardPosition: 9,
    activeMission: "Hold the Eclipse Gate",
    specialties: ["Fortress Aura", "Taunt Howl"],
    recentActions: ["Blocked siege ram", "Protected the high priestess"],
    progressToNextRank: 71,
    crescentBlessing: "Iron Crescent · Level 6"
  },
  {
    username: "MysticEcho",
    password: "songofmoon",
    profile: { fullName: "Lyriel 'Echo' Moonsong", role: "Member", highestRank: "Starlight Bard", favoriteHeroes: ["Moon Singer", "Harmony Wolf"], favoriteLanes: ["Support", "Mid"], privateProfileLink: "#", avatarIcon: "fa-music", quote: "The moon sings through me.", joined: "Cycle V", reputation: "MELODIC", lunarCredits: 14500, missionsComplete: 12 },
    stats: { agility: 74, strategy: 95, lunarPotency: 93, resilience: 65 },
    achievements: ["Siren's Grace", "Echoing Void"],
    tournamentsWon: ["Harmony Clash"],
    squadLeaderboardPosition: 10,
    activeMission: "Awaken the Lunar Harp",
    specialties: ["Healing Hymn", "Moonfall Sonata"],
    recentActions: ["Calmed rampaging beasts", "Performed at victory feast"],
    progressToNextRank: 22,
    crescentBlessing: "Melodic Crescent · Level 3"
  },
  {
    username: "VenomStrike",
    password: "serpentfang",
    profile: { fullName: "Zephyr 'Venom' Nox", role: "Member", highestRank: "Toxic Blademaster", favoriteHeroes: ["Serpent Queen", "Venom Wolf"], favoriteLanes: ["Jungle", "Mid"], privateProfileLink: "#", avatarIcon: "fa-snake", quote: "One drop is enough.", joined: "Cycle VI", reputation: "VENOMOUS", lunarCredits: 13200, missionsComplete: 17 },
    stats: { agility: 97, strategy: 78, lunarPotency: 75, resilience: 69 },
    achievements: ["Noxious", "Venomous Edge"],
    tournamentsWon: ["Serpent Cup"],
    squadLeaderboardPosition: 11,
    activeMission: "Infect the Abyssal water supply",
    specialties: ["Corrosive Bite", "Toxic Cloud"],
    recentActions: ["Poisoned enemy camp", "Stole antidote formula"],
    progressToNextRank: 37,
    crescentBlessing: "Venom Crescent · Level 4"
  },
  {
    username: "CrimsonMoon",
    password: "bloodhowl",
    profile: { fullName: "Vlad 'Crimson' Dusk", role: "Leader", highestRank: "Blood Moon Lord", favoriteHeroes: ["Vampire Wolf", "Crimson Reaper"], favoriteLanes: ["Top", "Jungle"], privateProfileLink: "#", avatarIcon: "fa-moon", quote: "The crimson tide rises.", joined: "Cycle II", reputation: "BLOODBORN", lunarCredits: 56700, missionsComplete: 51 },
    stats: { agility: 93, strategy: 89, lunarPotency: 96, resilience: 87 },
    achievements: ["Blood Moon", "Sanguine Conqueror", "Night Howler"],
    tournamentsWon: ["Crimson Gauntlet", "Blood Rite"],
    squadLeaderboardPosition: 2,  // tie? but we give unique
    activeMission: "Harvest the Lunar Eclipse",
    specialties: ["Blood Frenzy", "Moon's Bite"],
    recentActions: ["Led the Crimson March", "Defeated the Night King"],
    progressToNextRank: 83,
    crescentBlessing: "Blood Crescent · Level 8"
  },
  {
    username: "SilverPaw",
    password: "silverwolf",
    profile: { fullName: "Luna 'Silver' Grey", role: "Member", highestRank: "Moon Dancer", favoriteHeroes: ["Silver Wolf", "Lunar Dancer"], favoriteLanes: ["ADC", "Support"], privateProfileLink: "#", avatarIcon: "fa-paw", quote: "Swift as moonlight.", joined: "Cycle V", reputation: "SILVER", lunarCredits: 19500, missionsComplete: 22 },
    stats: { agility: 90, strategy: 80, lunarPotency: 86, resilience: 75 },
    achievements: ["Silver Streak", "Moonlit Acrobat"],
    tournamentsWon: ["Silver Stride"],
    squadLeaderboardPosition: 12,
    activeMission: "Retrieve the Silver Crescent",
    specialties: ["Moonstep", "Silver Shroud"],
    recentActions: ["Outran sentinels", "Delivered secret messages"],
    progressToNextRank: 41,
    crescentBlessing: "Silver Crescent · Level 5"
  },
  {
    username: "DuskWalker",
    password: "twilight",
    profile: { fullName: "Orin 'Dusk' Shadowalker", role: "Member", highestRank: "Twilight Ranger", favoriteHeroes: ["Dusk Wolf", "Shadow Archer"], favoriteLanes: ["Jungle", "Mid"], privateProfileLink: "#", avatarIcon: "fa-eye", quote: "Between light and dark.", joined: "Cycle IV", reputation: "TWILIGHT", lunarCredits: 22300, missionsComplete: 27 },
    stats: { agility: 92, strategy: 84, lunarPotency: 88, resilience: 79 },
    achievements: ["Twilight's Edge", "Shadow Walker"],
    tournamentsWon: ["Dusk Duel"],
    squadLeaderboardPosition: 13,
    activeMission: "Patrol the Twilight Border",
    specialties: ["Dusk Blink", "Eclipse Shot"],
    recentActions: ["Saved border outpost", "Intercepted dark ritual"],
    progressToNextRank: 53,
    crescentBlessing: "Dusk Crescent · Level 5"
  },
  {
    username: "AuroraFang",
    password: "northernlight",
    profile: { fullName: "Freya 'Aurora' Winterbloom", role: "Member", highestRank: "Aurora Guardian", favoriteHeroes: ["Lightweaver", "Prism Wolf"], favoriteLanes: ["Support", "ADC"], privateProfileLink: "#", avatarIcon: "fa-star-of-life", quote: "Colors of the moon.", joined: "Cycle VI", reputation: "RADIANT", lunarCredits: 17800, missionsComplete: 19 },
    stats: { agility: 82, strategy: 86, lunarPotency: 94, resilience: 73 },
    achievements: ["Prism Master", "Aurora Borealis"],
    tournamentsWon: ["Light Show"],
    squadLeaderboardPosition: 14,
    activeMission: "Collect Aurora Shards",
    specialties: ["Prism Barrier", "Aurora Beam"],
    recentActions: ["Illuminated dark caves", "Healed wounded allies"],
    progressToNextRank: 34,
    crescentBlessing: "Aurora Crescent · Level 4"
  },
  {
    username: "RuneWolf",
    password: "runic",
    profile: { fullName: "Elder Rune 'Runeweaver'", role: "Member", highestRank: "Runic Sage", favoriteHeroes: ["Spellbinder", "Ancient Wolf"], favoriteLanes: ["Mid", "Support"], privateProfileLink: "#", avatarIcon: "fa-scroll", quote: "Runes hold the truth.", joined: "Cycle III", reputation: "RUNIC", lunarCredits: 26400, missionsComplete: 31 },
    stats: { agility: 76, strategy: 97, lunarPotency: 95, resilience: 81 },
    achievements: ["Rune Breaker", "Seal Master"],
    tournamentsWon: ["Runic Convergence"],
    squadLeaderboardPosition: 15,
    activeMission: "Decode the Elder Runes",
    specialties: ["Runic Ward", "Ancient Seal"],
    recentActions: ["Unlocked hidden vault", "Deciphered prophecy"],
    progressToNextRank: 59,
    crescentBlessing: "Runic Crescent · Level 6"
  }
];

export function findMember(username, password) {
  return MEMBERS.find(m => m.username === username && m.password === password) || null;
}
